### ISSUE TITLE
Is this package deprecated?

### ISSUE THREAD

**Issue by clibassi** [prs-watch/Pitchjx.jl#11]
Hi there - this package looks very cool, but when I tried to replicate the example from the documentation using Julia 1.4.1 I get the following error: 

![image](https://user-images.githubusercontent.com/10570262/86399540-6d598400-bc75-11ea-8cdd-22a1735fe570.png)

Just wondering if the package is still maintained. 

Thanks!
CJ

**Comment by prs-watch** [comment]
@clibassi 

This is caused by ending of service of `gd2.mlb.com`. Any XMLs are no longer placed😢 

I'll try to make Julia package for `MLB Stats Api`, as MLB has started to support REST API for getting some data, including data that `Pitchjx.jl`. I'll replace `Pitchjx.jl` process by that, then this issue will be closed.

e.g. 
- http://statsapi.mlb.com/api/v1.1/game/566279/feed/live

**Comment by clibassi** [comment]
That sounds really great! Looking forward to it!

**Comment by prs-watch** [comment]
@clibassi 

**PROCESS SHARING**

I just created a package to execue MLB Stats API from Julia (not published to General repo yet). 

- https://github.com/prs-watch/MLBStatsAPI.jl

Then, I'll try to replace `Pitchjx.jl` process by using that.

**Comment by prs-watch** [comment]
Looks like my work almost done..

![image](https://user-images.githubusercontent.com/28729575/90947873-3da84a80-e474-11ea-8685-a186289328b4.png)

Then, I'll release packages step-by-step.

**Comment by prs-watch** [comment]
@clibassi 

`v0.1.0` is just released. It supports `MLB Stats API` by using [MLBStatsAPI.jl](https://github.com/prs-watch/MLBStatsAPI.jl). 

Although it hasn't released to general repo yet, you can try newest `Pitchjx.jl` by executing `Pkg.add(PackageSpec(path="https://github.com/prs-watch/Pitchjx.jl.git"))`. If you use it as soon as possible, try this way!

**Comment by prs-watch** [comment]
Here is my Jupyter Notebook script to test latest `Pitchjx.jl`.

---

```julia
using Pitchjx
```

    ┌ Info: Precompiling Pitchjx [aacb0929-27c6-5080-af7c-e887e16e4e49]
    └ @ Base loading.jl:1260



```julia
pitchjx("2018-07-01")
```

    ┌ Info: Initialize: Start
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/Pitchjx.jl:17
    ┌ Info: Initialize: Finish!
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/Pitchjx.jl:23
    ┌ Info: Extract dataset: Start
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/Pitchjx.jl:24
    ┌ Info: HTTP Status Code: 200
    └ @ MLBStatsAPI /opt/julia/packages/MLBStatsAPI/weUPo/src/MLBStatsAPI.jl:50
    ┌ Info: HTTP Status Code: 200
    └ @ MLBStatsAPI /opt/julia/packages/MLBStatsAPI/weUPo/src/MLBStatsAPI.jl:50
    ┌ Info: HTTP Status Code: 200
    └ @ MLBStatsAPI /opt/julia/packages/MLBStatsAPI/weUPo/src/MLBStatsAPI.jl:50
    ┌ Info: HTTP Status Code: 200
    └ @ MLBStatsAPI /opt/julia/packages/MLBStatsAPI/weUPo/src/MLBStatsAPI.jl:50
    ┌ Info: HTTP Status Code: 200
    └ @ MLBStatsAPI /opt/julia/packages/MLBStatsAPI/weUPo/src/MLBStatsAPI.jl:50
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Info: HTTP Status Code: 200
    └ @ MLBStatsAPI /opt/julia/packages/MLBStatsAPI/weUPo/src/MLBStatsAPI.jl:50
    ┌ Info: HTTP Status Code: 200
    └ @ MLBStatsAPI /opt/julia/packages/MLBStatsAPI/weUPo/src/MLBStatsAPI.jl:50
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Info: HTTP Status Code: 200
    └ @ MLBStatsAPI /opt/julia/packages/MLBStatsAPI/weUPo/src/MLBStatsAPI.jl:50
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Info: HTTP Status Code: 200
    └ @ MLBStatsAPI /opt/julia/packages/MLBStatsAPI/weUPo/src/MLBStatsAPI.jl:50
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Info: HTTP Status Code: 200
    └ @ MLBStatsAPI /opt/julia/packages/MLBStatsAPI/weUPo/src/MLBStatsAPI.jl:50
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Info: HTTP Status Code: 200
    └ @ MLBStatsAPI /opt/julia/packages/MLBStatsAPI/weUPo/src/MLBStatsAPI.jl:50
    ┌ Info: HTTP Status Code: 200
    └ @ MLBStatsAPI /opt/julia/packages/MLBStatsAPI/weUPo/src/MLBStatsAPI.jl:50
    ┌ Info: HTTP Status Code: 200
    └ @ MLBStatsAPI /opt/julia/packages/MLBStatsAPI/weUPo/src/MLBStatsAPI.jl:50
    ┌ Info: HTTP Status Code: 200
    └ @ MLBStatsAPI /opt/julia/packages/MLBStatsAPI/weUPo/src/MLBStatsAPI.jl:50
    ┌ Info: HTTP Status Code: 200
    └ @ MLBStatsAPI /opt/julia/packages/MLBStatsAPI/weUPo/src/MLBStatsAPI.jl:50
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Warning: At least one column data cannot be extracted. This row will be skipped from result dataframe.
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/extractor.jl:115
    ┌ Info: HTTP Status Code: 200
    └ @ MLBStatsAPI /opt/julia/packages/MLBStatsAPI/weUPo/src/MLBStatsAPI.jl:50
    ┌ Info: Extract dataset: Finish!
    └ @ Pitchjx /opt/julia/packages/Pitchjx/xTrqf/src/Pitchjx.jl:26





<table class="data-frame"><thead><tr><th></th><th>date</th><th>pitcherid</th><th>pitcher_teamid</th><th>pitcher_firstname</th><th>pitcher_lastname</th><th>pitcher_teamname</th></tr><tr><th></th><th>String</th><th>Int64</th><th>Int64</th><th>String</th><th>String</th><th>String</th></tr></thead><tbody><p>4,482 rows × 30 columns (omitted printing of 24 columns)</p><tr><th>1</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>2</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>3</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>4</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>5</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>6</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>7</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>8</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>9</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>10</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>11</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>12</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>13</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>14</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>15</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>16</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>17</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>18</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>19</th><td>20180701</td><td>592332</td><td>110</td><td>Kevin</td><td>Gausman</td><td>Baltimore Orioles</td></tr><tr><th>20</th><td>20180701</td><td>592547</td><td>108</td><td>William</td><td>McGuire</td><td>Los Angeles Angels</td></tr><tr><th>21</th><td>20180701</td><td>592547</td><td>108</td><td>William</td><td>McGuire</td><td>Los Angeles Angels</td></tr><tr><th>22</th><td>20180701</td><td>592547</td><td>108</td><td>William</td><td>McGuire</td><td>Los Angeles Angels</td></tr><tr><th>23</th><td>20180701</td><td>592547</td><td>108</td><td>William</td><td>McGuire</td><td>Los Angeles Angels</td></tr><tr><th>24</th><td>20180701</td><td>592547</td><td>108</td><td>William</td><td>McGuire</td><td>Los Angeles Angels</td></tr><tr><th>25</th><td>20180701</td><td>592547</td><td>108</td><td>William</td><td>McGuire</td><td>Los Angeles Angels</td></tr><tr><th>26</th><td>20180701</td><td>592547</td><td>108</td><td>William</td><td>McGuire</td><td>Los Angeles Angels</td></tr><tr><th>27</th><td>20180701</td><td>592547</td><td>108</td><td>William</td><td>McGuire</td><td>Los Angeles Angels</td></tr><tr><th>28</th><td>20180701</td><td>592547</td><td>108</td><td>William</td><td>McGuire</td><td>Los Angeles Angels</td></tr><tr><th>29</th><td>20180701</td><td>592547</td><td>108</td><td>William</td><td>McGuire</td><td>Los Angeles Angels</td></tr><tr><th>30</th><td>20180701</td><td>592547</td><td>108</td><td>William</td><td>McGuire</td><td>Los Angeles Angels</td></tr><tr><th>&vellip;</th><td>&vellip;</td><td>&vellip;</td><td>&vellip;</td><td>&vellip;</td><td>&vellip;</td><td>&vellip;</td></tr></tbody></table>

**Comment by prs-watch** [comment]
@clibassi 

If it works well, please close issue 🙇

**Comment by clibassi** [comment]
> @clibassi
> 
> `v0.1.0` is just released. It supports `MLB Stats API` by using [MLBStatsAPI.jl](https://github.com/prs-watch/MLBStatsAPI.jl).
> 
> Although it hasn't released to general repo yet, you can try newest `Pitchjx.jl` by executing `Pkg.add(PackageSpec(path="https://github.com/prs-watch/Pitchjx.jl.git"))`. If you use it as soon as possible, try this way!

Hey - thanks so much for this - and I'm trying it out but getting an error that "PackageSpec not defined" - here's the code I'm using and my versioninfo: 

`import Pkg; Pkg.add(PackageSpec(path="https://github.com/prs-watch/Pitchjx.jl.git"))`

Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8

**Comment by prs-watch** [comment]
Hmm, that's weired. My code is following, which is executed on Julia v1.5.0. 

```julia
using Pkg
Pkg.add(PackageSpec(path="https://github.com/prs-watch/Pitchjx.jl.git"))
```

But right now, `Pitchjx` v0.1.0 is [deployed](https://github.com/JuliaRegistries/General/pull/20172) to General Repo! So you can do that.

```julia
using Pkg
Pkg.add("Pitchjx")
```

Could you try it?

**Comment by clibassi** [comment]
Hmmm - so I just gave it a try and got this error: 

![image](https://user-images.githubusercontent.com/10570262/91609872-325a9080-e946-11ea-9cc9-5be52e8c2272.png)

**Comment by prs-watch** [comment]
Thanks for reporting. Though it's error which depends on `HTTP.jl` (as Python `requests` returns 200 same URL), I'll check it.

![image](https://user-images.githubusercontent.com/28729575/91630619-b592e980-ea0d-11ea-83f1-b1cbcd801a59.png)

**Comment by prs-watch** [comment]
This is weird. As I [commented](https://github.com/prs-watch/Pitchjx.jl/issues/11#issuecomment-680115563), it worked fine w/ `HTTP` 0.8.17. HTTP status code tells us that this is Statsapi REST server error, but it looks like trouble depends on HTTP client.. Maybe it will take a lot of time to solve this.

**Comment by clibassi** [comment]
Okay - no trouble. I didn't want to cause you a ton of work - should I close it out?

**Comment by prs-watch** [comment]
@clibassi 

Sorry for late my reply. Looks like HTTP works well again. 

![image](https://user-images.githubusercontent.com/28729575/92987161-de7da900-f4fa-11ea-8601-2eebcbb3f923.png)

**Comment by clibassi** [comment]
This worked great for me - thanks so much for this! 

Going to close the issue.
